language: java
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8

#enable caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/ibm-jdk-installer/

install: true
script:
  - ./gradlew :inspectit-oce-agent:systemTest

jobs:
  include:
    - name: "JDK ibmjdk8 Java"
      sudo: true
      install:
        - wget -nc -O $HOME/ibm-jdk-installer/ibm-sdk.bin https://s3-eu-west-1.amazonaws.com/inspectit-oce-files/ibm-java-sdk-8.0-5.26-x86_64-archive.bin || true
        - sudo chmod +x $HOME/ibm-jdk-installer/ibm-sdk.bin
        - echo "INSTALLER_UI=silent" > $HOME/ibm-install.properties
        - echo "USER_INSTALL_DIR=$HOME/ibm-jdk-8" >> $HOME/ibm-install.properties
        - echo "LICENSE_ACCEPTED=TRUE" >> $HOME/ibm-install.properties
        - export PS1=">"
        - sudo $HOME/ibm-jdk-installer/ibm-sdk.bin -i silent -f $HOME/ibm-install.properties
        - sudo update-alternatives --install "/usr/bin/java" "java" "$HOME/ibm-jdk-8/bin/java" 1
        - sudo update-alternatives --set "java" "$HOME/ibm-jdk-8/bin/java"
        - sudo update-alternatives --install "/usr/bin/javac" "javac" "$HOME/ibm-jdk-8/bin/javac" 1
        - sudo update-alternatives --set "javac" "$HOME/ibm-jdk-8/bin/javac"
        - export JAVA_HOME=$HOME/ibm-jdk-8
        - java -version
      script: ./gradlew :inspectit-oce-agent:systemTest

    - stage: deploy
      name: "Code Coverage Reporting"
      jdk: oraclejdk8
      install: ./gradlew build codeCoverageReport
      script:
        # upload coverage report
        - bash <(curl -s https://codecov.io/bash)

    - name: "Documentation Deployment"
      jdk: oraclejdk8
      install: ./gradlew :inspectit-oce-documentation:asciidoctor
      script: skip
      deploy:
        # MASTER BUILDS
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "docs.inspectit.rocks"
          region: eu-west-1
          skip_cleanup: true
          local_dir: inspectit-oce-documentation/build/asciidoc/html5
          upload-dir: master
          on:
            tags: false
            branch: master
        # RELEASE BUILDS
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "docs.inspectit.rocks"
          region: eu-west-1
          skip_cleanup: true
          local_dir: inspectit-oce-documentation/build/asciidoc/html5
          upload-dir: releases/latest
          on:
            tags: true
            branch: master
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "docs.inspectit.rocks"
          region: eu-west-1
          skip_cleanup: true
          local_dir: inspectit-oce-documentation/build/asciidoc/html5
          upload-dir: releases/$TRAVIS_TAG
          on:
            tags: true
            branch: master


stages:
  - test
  - name: deploy
    if: repo = inspectIT/inspectit-oce