[versions]
ioJsonwebtoken = "0.12.6"
orgEclipseJgit = "7.0.0.202409031743-r"
orgMockito = "5.12.0"
orgJunitJupiter = "5.10.3"
orgSpringframeworkBoot = { strictly = "3.3.5" }
orgSpringframeworkSecurity = "6.3.4"

[libraries]
comGoogleCodeGson = "com.google.code.gson:gson:2.11.0"
comGoogleGuava = { module = "com.google.guava:guava", version = { strictly = "33.2.1-jre" } }
comH2databaseH2 = "com.h2database:h2:2.3.232"
commonsIo = "commons-io:commons-io:2.16.1"
ioJsonwebtokenJjwtApi = { module = "io.jsonwebtoken:jjwt-api", version.ref = "ioJsonwebtoken" }
ioJsonwebtokenJjwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "ioJsonwebtoken" }
ioJsonwebtokenJjwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "ioJsonwebtoken" }
orgApacheCommonsCommonsLang3 = "org.apache.commons:commons-lang3:3.14.0"
orgAwaitility = "org.awaitility:awaitility:4.2.2"
orgEclipseJgitOrgEclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
orgEclipseJgitOrgEclipseJgitSshApache= {module = "org.eclipse.jgit:org.eclipse.jgit.ssh.apache", version.ref = "orgEclipseJgit" }
orgFlywaydbFlywayCore = "org.flywaydb:flyway-core:10.21.0"
orgHibernateOrmHibernateCommunityDialects = "org.hibernate.orm:hibernate-community-dialects:6.6.2.Final"
orgJunitJupiterJunitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "orgJunitJupiter" }
orgJunitJupiterJunitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "orgJunitJupiter" }
orgJunitJupiterJunitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "orgJunitJupiter" }
orgMockitoMockitoJunitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "orgMockito" }
orgSpringframeworkBootSpringBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "orgSpringframeworkBoot" }
orgSpringframeworkBootSpringBootStarterDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "orgSpringframeworkBoot" }
orgSpringframeworkBootSpringBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "orgSpringframeworkBoot" }
orgSpringframeworkBootSpringBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "orgSpringframeworkBoot" }
orgSpringframeworkBootSpringBootStartervalidation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "orgSpringframeworkBoot" }
orgSpringframeworkLdapSpringLdapCore = "org.springframework.ldap:spring-ldap-core:3.2.7"
orgSpringframeworkSecuritySpringSecurityLdap = { module = "org.springframework.security:spring-security-ldap", version.ref = "orgSpringframeworkSecurity" }
orgSpringframeworkSecuritySpringSecurityTest = { module = "org.springframework.security:spring-security-test", version.ref = "orgSpringframeworkSecurity" }
orgSpringframeworkSecuritySpringSecurityWeb = { module = "org.springframework.security:spring-security-web", version.ref = "orgSpringframeworkSecurity" }
orgSpringframeworksecuritySpringSecurityConfig = { module = "org.springframework.security:spring-security-config", version.ref = "orgSpringframeworkSecurity" }
chQosLogbackLogbackClassic = "ch.qos.logback:logback-classic:1.5.12"
chQosLogbackLogbackCore = "ch.qos.logback:logback-core:1.5.12"
orgXerialSqliteJdbc = "org.xerial:sqlite-jdbc:3.47.0.0"
orgYamlSnakeyaml = "org.yaml:snakeyaml:2.3"

[bundles]
jgit = [
    "orgEclipseJgitOrgEclipseJgit",
    "orgEclipseJgitOrgEclipseJgitSshApache"
]
jsonwebtoken = [
    "ioJsonwebtokenJjwtApi",
    "ioJsonwebtokenJjwtImpl",
    "ioJsonwebtokenJjwtJackson",
]

[plugins]
ioSpringDependencyManagement = "io.spring.dependency-management:1.1.6"
orgSpringframeworkBoot = { id = "org.springframework.boot", version.ref = "orgSpringframeworkBoot" }
