
inspectit:
  metrics:
    definitions:
      '[entrypoint/invocations]':
        unit: invocations
        views:
          '[entrypoint/invocations]':
            aggregation: COUNT
            tags: {method_name : true}


  instrumentation:
    data:
      entry_point_found:
        is-tag: false
      is_entry_point:
        down-propagation: NONE
        is-tag: false
      method_name:
        down-propagation: NONE

    scopes:
      EntryPointDetectionTest-methods:
        type:
          name: EntryPointDetectionTest
          matcher-mode: ENDS_WITH
        methods:
          - name: methodA
          - name: methodB

    rules:
      EntryPointDetectionTest-methods:
        scopes:
          EntryPointDetectionTest-methods: true
        entry:
          method_name: {action: get_method_name}
          entry_point_found: {action: set, constant-input: {value: true}}
          is_entry_point:
            only-if-null: entry_point_found
            order:
              reads-before-written:
                entry_point_found : true
            action: set
            constant-input: {value: 1}
        metrics:
          '[entrypoint/invocations]': is_entry_point
