# overwrite settings from default.yml for system tests
inspectit:
  instrumentation:
    scopes:
      NamedElement-doSomething:
        interfaces:
          - name: rocks.inspectit.ocelot.instrumentation.NamedElement
        methods:
          - name: doSomething
        advanced:
          instrument-only-inherited-methods : true

    rules:
      InstrumentationScopesTest-read-name-of-NamedElement:
        scopes:
          NamedElement-doSomething: true
        entry:
          #defined in GenericActionsTest.yml
          name: { action: readNameViaThis }

