# my global config
global:
  scrape_interval: 1s

scrape_configs:
- job_name: inspectit
  # scrape_interval is defined by the configured global (15s).
  # scrape_timeout is defined by the global default (10s).

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  - targets: ['customers-service:9091', 'visits-service:9092','vets-service:9093','api-gateway:9094','discovery-server:9095','config-server:9096', 'ocelot-eum-server:9097']