# overwrite settings from default.yml for system tests
inspectit:
  publish-opencensus-to-bootstrap: true
  self-monitoring:
    enabled: true
  logging:
    debug: true
  instrumentation:
    internal:
      # defines how often the agent should check if new classes have been defined.
      # this check is only performed if Classloader.defineClass was called less than ${max-class-definition-delay} seconds ago
      new-class-discovery-interval: 100ms
      # defines how often after the last invocation of a ClassFileTransformer the agent scans for new classes
      num-class-discovery-trials: 5

    data-providers:
#-----------------------DataProvidersTest.verifyArgumentsAccessible ------------------------
      readNameViaArg0:
        imports:
          - rocks.inspectit.oce.instrumentation
        input:
          arg0: NamedElement
        value: arg0.getName()
      readNameViaArgs:
        imports:
          - rocks.inspectit.oce.instrumentation
        input:
          args: Object[]
        value: ((NamedElement)args[0]).getName()
      reverse:
        input:
          str: String
        value-body: |
          StringBuilder sb =  new StringBuilder(str);
          sb.reverse();
          return sb.toString();
      toUpperCase:
        input:
          str: String
        value: str.toUpperCase()
#-----------------------DataProvidersTest.verifyArgumentsAccessible ------------------------
      addDurationToArg:
        imports:
          - java.time
        input:
          args: Object[]
          argIndex : int
          durationToAdd: Duration
        value: new Long( ((Duration)(args[argIndex])).toMillis() + durationToAdd.toMillis() )
#-----------------------DataProvidersTest.testDefaultMethodInstrumented ------------------------
      readNameViaThis:
        imports:
          - rocks.inspectit.oce.instrumentation
        input:
          thiz: NamedElement
        value: thiz.getName()

    scopes:
      DataProvidersTest-argumentAccessTest:
        type:
          name: DataProvidersTest
          matcher-mode: ENDS_WITH
        methods:
          - name: argumentAccessTest
      DataProvidersTest-constantParsingTest:
        type:
          name: rocks.inspectit.oce.instrumentation.DataProvidersTest
        methods:
          - name: constantParsingTest
      NamedElement-doSomething:
        interfaces:
          - name: rocks.inspectit.oce.instrumentation.NamedElement
        methods:
          - name: doSomething
        advanced:
          instrument-only-inherited-methods : true
    rules:
      DataProvidersTest-argumentAccessTest:
        scopes:
          DataProvidersTest-argumentAccessTest: true
        entry:
          name_via_arg0: {provider: readNameViaArg0}
          name_via_args: {provider: readNameViaArgs}
          name_reversed: {provider: reverse, data-input: {str : name_via_arg0}}
          name_reversed_upper: {provider: toUpperCase, data-input: {str : name_reversed}}
      DataProvidersTest-constantParsingTest:
        scopes:
          DataProvidersTest-constantParsingTest: true
        entry:
          result:
            provider: addDurationToArg
            constant-input:
              argIndex: 0
              durationToAdd: "2s"

      InstrumentationScopesTest-read-name-of-NamedElement:
        scopes:
          NamedElement-doSomething: true
        entry:
          name: { provider: readNameViaThis }

