# See https://github.com/inspectIT/inspectit-oce/blob/0.1.M1/inspectit-oce-core/src/main/resources/config/default.yml
# for all the configuration options.
inspectit:
  metrics:
    # root setting for the polling frequency of all metrics
    # when a metrics has no frequency defined separately, this frequency will be used
    frequency: 1s