inspectit:

  # the name of the service which is being instrumented
  service-name: "InspectIT Agent"

  # defines common tags to be be set on the metrics
  tags:
    # different tag providers that can be configured
    providers:
      # environment provider adds 'service-name', 'host' and 'host-address' tags
      environment:
        # if environment provider is enabled
        enabled: true
        # should the host name be resolved using InetAddress.getLocalHost(), if false 'host' tag is not added by env provider
        resolve-host-name: true
        # should the host address be resolved using InetAddress.getLocalHost(), if false 'host-address' tag is not added by env provider
        resolve-host-address: true

    # specifies user defined tag keys and values as a map
    # these tag values would overwrite any value added by the providers, thus you can easily overwrite tags values by your own
    # extra:

  # all configurations sources
  config:
    # file based configuration - has the highest priority
    # loads all .yaml/yml and .properties files in alphabetical order from the given path
    # is active when path is not empty or null and enabled is set to true
    file-based:
      # the path to the directory to scan for configuration files
      # scanning happens non-recursive meaning that no subdirectories will be parsed
      path:
      # can be used to disable the file based configuration while the path is still specified
      enabled: true
      # if true the directory will be watched for changes. When changes occur, the configuration is automatically reloaded
      watch: true

  # settings for configuring OpenCensus stats and trace exporters
  exporters:
    # settings for metrics exporters
    metrics:
      # settings for the prometheus exporter (https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/prometheus)
      prometheus:
        # if true, the agent will try to start the Prometheus stats exporter
        enabled: true
        # the hostname or IP-address on which the /metrics endpoint of prometheus will be started.
        host: localhost
        # the port on which the /metrics endpoint of prometheus will be started
        port: 8888

  # general settings regarding metrics capturing
  metrics:
    # master switch for metrics capturing. When set to false the following happens:
    #  - all metrics exporters are disabled
    enabled: true

  # logging settings
  logging:
      # path to a custom user-specified logback config file that should be used
      config-file:
      # properties below only work if the default inspectIT OCE logback config file is used
      # sets the inspectIT OCE log level to TRACE
      trace: false
      # sets the level to DEBUG (only if trace is false)
      debug: false
      # settings for the console output
      console:
        # defines if the console output is enabled
        enabled: true
        # defines a custom pattern to output to the console
        pattern:
      # settings for the file-based log output
      # inspectIT OCE will create two log files: agent.log and exceptions.log
      file:
        # defines if the file-based log output is enabled
        enabled: true
        # defines a custom pattern to output to the console
        pattern:
        # defines a custom path where log files should be placed (defaults to /tmp/inspectit-oce)
        path:
        # if the default pattern should include the service name (specified with inspectit.service-name)
        # helpful when you run more than one service on the same host
        include-service-name: true

  # defines how many threads inspectIT may start for its internal tasks
  thread-pool-size: 2

  # If true, the OpenCensus API and Implementation will be loaded by the bootstrap classloader.
  # Otherwise they will be loaded by the private inspectIT classloader.
  publish-opencensus-to-bootstrap: false